### ISSUE TITLE
Logo & Graphics

### ISSUE THREAD

**Issue by neynah** [iwazaru/polytunes#3]
Hi there! I'd love to get started on graphics. If you visit our [app market](https://apps.sandstorm.io/) you'll see that each app has an icon/logo. 

Additionally on Sandstorm (Oasis) each app also has a launcher icon and a small mini grain icon on the left sidebar:
![image](https://cloud.githubusercontent.com/assets/855341/11043757/27e7be46-86d3-11e5-91bf-c069df698af8.png)

You're also free to use any graphics I produce for your project for non-Sandstorm related things. Let me know if you have any ideas, else I'll spend some time looking at your app and come up with something appropriate. :)

**Comment by clemlatz** [comment]
Well actually, Polytunes does have a logo!

![Polytunes logo](http://polytun.es/icons/favicon-196x196.png)

Okay, I made in five minutes using... Polytunes. So it sure can be improved! Especially, it doesn't work well as 16x16 favicon, it just look like a black square. I like the idea of using pixel art, though, as that's what you end up with when you play Polytunes. But if you have other ideas, no problem. Surprise me!

**Comment by neynah** [comment]
! That's wonderful. I can work with this. The favicon can be very similar just with fewer pixels and less padding around the edges. Could you share the source file / larger image?

**Comment by clemlatz** [comment]
Well the source file is just a screen capture of Polytunes and it's not very large, but here it comes!

![yellow note](https://cloud.githubusercontent.com/assets/5627688/11047370/54823468-8732-11e5-92cb-819bc761d629.png)

**Comment by neynah** [comment]
Perfect! This will do. :hatched_chick:

**Comment by neynah** [comment]
Quick & easy when you have your own graphics:
![image](https://cloud.githubusercontent.com/assets/855341/11047608/4a55c076-86e8-11e5-9eb6-dce9cb27a2dd.png)

Let me know if this looks good, if not I can be more creative.

**Comment by neynah** [comment]
I guess the favicon actually has less contrast/ the yellow is not as visible. I might increase the contrast with a brighter yellow or get rid of the black grid altogether (but this option sounds boring because I like the grid).

**Comment by clemlatz** [comment]
Exactly my thoughts. Maybe using white instead of yellow would make it more readable ?

**Comment by neynah** [comment]
![image](https://cloud.githubusercontent.com/assets/855341/11048021/51de2f2a-86ea-11e5-8d7a-c08d5deafa62.png)

**Comment by clemlatz** [comment]
The yellow one looks great!
